### ISSUE TITLE
Build version cannot call bot players

### ISSUE THREAD

**Issue by Tjorriemorrie** [EntelectChallenge/2015-SpaceInvaders-TestHarness#6] opened 2015-04-20 17:26 UTC
I'm using the build version 1.0.0: SpaceInvadersDuel.exe. From what I understand it should run `run.bat %1` in the player1 and player2 folders. I have my plain set up in player 1 folder, which does [not work](https://github.com/EntelectChallenge/2015-SpaceInvaders-Bot-Python/issues/1) and the initial default player2 given in the build. The default player2 output is also the error:

```
/c: /c: is a directory
[GAME]  Bot Player 2 finished in 34 ms.
[GAME]  Process exited with non-zero code 126 from player Player 2.
[GAME]  No output file from player Player 2
```

I have installed the .net framework. What am I doing wrong here?

**Comment by Tjorriemorrie** [comment] 2015-04-24 17:53
Still receiving the non-zero exits from v1.0.1.

Running win8 and installed the .net framework link provided in readme.

**Comment by mattpwest** [comment] 2015-04-24 19:55
I haven't been able to reproduce this with either version on Win7 with Python 2.7.9 - I've found someone else at the office with Win8 that are willing to try it - will let you know if we learn anything from that.

**Comment by Tjorriemorrie** [comment] 2015-04-25 11:21
I've installed Visual Studio but I'm not sure how to debug this: I've copied over the player folders from the build to the bin/debug folder, but when I run a debug instance there doesn't seem to be any specific errors. I tried to look at the code but only got as far as AddEventHandlersToProcess but now I'm not sure where the memory logwriter goes. If you can give me some broad guidelines on debugging this I can try from my side.

**Comment by Tjorriemorrie** [comment] 2015-05-02 07:45
@mattpwest Did the person manage to run it on Win8?

**Comment by mattpwest** [comment] 2015-05-03 09:12
@Tjorriemorrie Yes, no problems on their machine... :(

Starting to wonder if it's something really fundamental that I'm missing...

What console are you using? Is it standard cmd.exe or are you using something like Git Bash? I know I had problems at one point with some unprintable characters in the .bat files after editing them in Visual Studio - it may be worth trying in plain cmd.exe if you were using Git Bash.

**Comment by Tjorriemorrie** [comment] 2015-05-03 13:01
```
Warning 1   The 'packages' element is not declared. C:\projects\2015-SpaceInvaders-TestHarness\SpaceInvadersDuel\packages.config    3   2   SpaceInvadersDuel
```

Does that mean anything?

**Comment by mattpwest** [comment] 2015-05-03 17:52
From some Googling that just sounds like VS being unable to validate the NuGet packages config xml file.

**Comment by mattpwest** [comment] 2015-05-10 21:52
@Tjorriemorrie Could you please try the new 1.0.2 release?

There were some patches contributed that tweaked how the runner handles killing a bot and querying the bot exit code, which may make a difference given that yours was reporting a weird exit code...

**Comment by mattpwest** [comment] 2015-05-22 05:32
Closing this issue due to lack of any further feedback.

**Closed as completed by mattpwest** 2015-05-22 05:32 UTC
Labels: cannot reproduce

**Comment by Tjorriemorrie** [comment] 2015-05-22 07:28
That didn't work.

I found a vm to use to work around it.

**Comment by Locefir** [comment] 2021-11-19 09:14
defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1
